version: '3'

# version 3 can be used with docker stack deploy --compose-file=docker-compose.yml stack-name
# images must be prebuilt

networks:
  kovasbak:
    driver: overlay

services:

  zookeeper:
    image: kovasbak-zookeeper:latest
    networks:
      - kovasbak
    deploy:
      mode: replicated
      replicas: 1

  kafkabroker:
    image: kovasbak-kafkabroker:latest
    command: ["--override", "zookeeper.connect=zookeeper:2181"]
    networks:
      - kovasbak
    deploy:
      mode: replicated
      replicas: 1

  kovasbak:
    image: kovasbak:latest
    command: ["--spring.kafka.bootstrap-servers=kafkabroker:9092"]
    ports:
      - "8080:8080"
    networks:
      - kovasbak
    deploy:
      mode: replicated
      replicas: 1
